# -*- coding: utf-8 -*-
"""web_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nwXeUCb39fAQ8vRnvPLlBdXHTEwhYEx2
"""

import requests
url='https://groceries.aldi.co.uk/en-GB/Search?keywords=butter'
response = requests.get(url)
print(response)
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.title)

# Web Scraping for Aldi
import requests
from bs4 import BeautifulSoup

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47','Connection': 'keep-alive','Cache-Control': 'max-age=0','Upgrade-Insecure-Requests': '1',
'Accept-Encoding': 'gzip, deflate',
'Accept-Language': 'en-US,en;q=0.9',
'Cookie': 'AuthSession=dddddd'}

r = requests.get('https://www.ocado.com/search?entry=butter', headers=HEADERS)

soup = BeautifulSoup(r.text, 'html.parser')
print(soup.title)

items = soup.findAll('div', attrs={"class":"fop-item"})
print(items)
for item in items:
    name = item.find("h4", class_="fop-title")
    price = item.find("span", class_="fop-price")

    print(name.text)
    print(price.text)
    print('\n')

print(r)

supermarkets = [
    {
      'shop': 'Tesco',
      'item': 'product-list--list-item',
      'name': 'ldbwMG',
      'price': 'jWPEtj',
      'url': 'https://www.tesco.com/groceries/en-GB/search?query='
    },
    {
      'shop': 'M&S',
      'item': 'fop-item',
      'name': 'fop-title',
      'price': 'fop-price',
      'url': 'https://www.ocado.com/search?entry='
    }, 
    'Asda',
    'Waitrose', 
    'M&S',
    'Coop', 
    'Sainsburys', 
    'Morrisons', 
    'Iceland'
    ]

# Web Scraping for Tesco
import requests
from bs4 import BeautifulSoup

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47','Connection': 'keep-alive','Cache-Control': 'max-age=0','Upgrade-Insecure-Requests': '1',
'Accept-Encoding': 'gzip, deflate',
'Accept-Language': 'en-US,en;q=0.9',
'Cookie': 'AuthSession=dddddd'}

r = requests.get('https://www.tesco.com/groceries/en-GB/search?query=bread', headers=HEADERS)

soup = BeautifulSoup(r.text, 'html.parser')
print(soup.title)

items = soup.findAll('li', attrs={"class":"product-list--list-item"})
print(items)
for item in items:
    name = item.find("span", class_="ldbwMG")
    price = item.find("p", class_="jWPEtj")

    print(name.text)
    print(price.text)
    print('\n')

print(r)

import requests

response = requests.get(
  url='https://proxy.scrapeops.io/v1/',
  params={
      'api_key': 'c17b7c28-a3dc-46d4-b904-382e6e910362',
      'url': 'https://groceries.asda.com/search/butter', 
      'headers' : {'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148'}
  },
)

soup = BeautifulSoup(response.text, 'html.parser')
print(soup.title)

items = soup.findAll('a', attrs={"class":"co-product__anchor"})
print(items)